@startuml
'https://plantuml.com/class-diagram

class guitar
{
serialNumber: String
Price: double
builder: String
model: String
Type: String
backWood: String
topWood: String
}

class Inventory
{
Guitars: List
+addGuitar(String, double, String, String, String, String, String)
search(Guitar)
}

@enduml